/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-26 11:35:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<title>요리조리.com</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header class=\"bg-dark py-5\">\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<h1 class=\"display-4 fw-bolder text-warning\">요리조리</h1>\r\n");
      out.write("				<h1 class=\"display-4 fw-bolder\">요리책 서비스</h1>\r\n");
      out.write("				<p class=\"lead fw-normal text-white-50 mb-0\">세상의 모든 레시피</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- Section-->\r\n");
      out.write("	<section class=\"py-5\">\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col mb-5\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<!-- Sale badge-->\r\n");
      out.write("						<div class=\"badge bg-dark text-white position-absolute\"\r\n");
      out.write("							style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("						<!-- Product image-->\r\n");
      out.write("						<img class=\"card-img-top\"\r\n");
      out.write("							src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("						<!-- Product details-->\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<!-- Product name-->\r\n");
      out.write("								<h5 class=\"fw-bolder\">요리책 이름</h5>\r\n");
      out.write("								<!-- Product price-->\r\n");
      out.write("								요리책 설명\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Product actions-->\r\n");
      out.write("						<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<a class=\"btn btn-outline-dark mt-auto\" href=\"#\">상세보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Footer-->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- Bootstrap core JS-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Core theme JS-->\r\n");
      out.write("	<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
