/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-26 10:24:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.error;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import namoo.yorizori.common.web.YZRuntimeException;

public final class error_005f500_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("namoo.yorizori.common.web.YZRuntimeException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Yorizori</title>\r\n");
      out.write("<link\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("  rel=\"stylesheet\"\r\n");
      out.write("  integrity=\"sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/assets/img/favicons/apple-touch-icon.png\"\r\n");
      out.write("  sizes=\"180x180\">\r\n");
      out.write("<link rel=\"icon\"\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/assets/img/favicons/favicon-32x32.png\"\r\n");
      out.write("  sizes=\"32x32\" type=\"image/png\">\r\n");
      out.write("<link rel=\"icon\"\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/assets/img/favicons/favicon-16x16.png\"\r\n");
      out.write("  sizes=\"16x16\" type=\"image/png\">\r\n");
      out.write("<link rel=\"manifest\"\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/assets/img/favicons/manifest.json\">\r\n");
      out.write("<link rel=\"mask-icon\"\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/assets/img/favicons/safari-pinned-tab.svg\"\r\n");
      out.write("  color=\"#712cf9\">\r\n");
      out.write("<link rel=\"icon\"\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/assets/img/favicons/favicon.ico\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#712cf9\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("	font-size: 1.125rem;\r\n");
      out.write("	text-anchor: middle;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("	.bd-placeholder-img-lg {\r\n");
      out.write("		font-size: 3.5rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-divider {\r\n");
      out.write("	height: 3rem;\r\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\r\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\r\n");
      out.write("	border-width: 1px 0;\r\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\r\n");
      out.write("		rgba(0, 0, 0, .15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-vr {\r\n");
      out.write("	flex-shrink: 0;\r\n");
      out.write("	width: 1.5rem;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bi {\r\n");
      out.write("	vertical-align: -.125em;\r\n");
      out.write("	fill: currentColor;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	height: 2.75rem;\r\n");
      out.write("	overflow-y: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller .nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	padding-bottom: 1rem;\r\n");
      out.write("	margin-top: -1px;\r\n");
      out.write("	overflow-x: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	-webkit-overflow-scrolling: touch;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-sheet .modal-dialog {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	transition: bottom .75s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-sheet .modal-footer {\r\n");
      out.write("	padding-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-alert .modal-dialog {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-tour .modal-dialog {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link\r\n");
      out.write("  href=\"https://getbootstrap.com/docs/5.2/examples/sign-in/signin.css\"\r\n");
      out.write("  rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"text-center\">\r\n");
      out.write("  <div\r\n");
      out.write("    class=\"modal modal-sheet position-static d-block bg-secondary py-5\"\r\n");
      out.write("    tabindex=\"-1\" role=\"dialog\" id=\"modalSheet\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("      <div class=\"modal-content rounded-4 shadow\">\r\n");
      out.write("        <div class=\"modal-header border-bottom-0\">\r\n");
      out.write("          <h5 class=\"modal-title\">로그인 에러</h5>\r\n");
      out.write("          <a href=\"\" class=\"btn-close\"\r\n");
      out.write("            data-bs-dismiss=\"modal\" aria-label=\"Close\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body py-2\">\r\n");
      out.write("          <p>");
      out.print(exception.getMessage() );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer flex-column border-top-0\">\r\n");
      out.write("          \r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("          ");

          YZRuntimeException ex = (YZRuntimeException)exception;
          String redirectURL = ex.getRedirectURL();
          if(redirectURL != null){
          
      out.write("\r\n");
      out.write("          <a href=\"");
      out.print(redirectURL );
      out.write("\" class=\"btn btn-lg btn-primary w-40 mx-0 mb-2\">확인</a>\r\n");
      out.write("          ");

          }else{
          
      out.write("\r\n");
      out.write("          <a href=\"javascript:history.back();\" class=\"btn btn-lg btn-primary w-40 mx-0 mb-2\">확인</a>\r\n");
      out.write("          ");
            
          }
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
